"""Big Update

Revision ID: 612519fa98ff
Revises: 20260424_0001
Create Date: 2026-04-25 00:03:17.432524
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '612519fa98ff'
down_revision: Union[str, None] = '20260424_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'featured_images',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.drop_index(op.f('idx_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_location_id'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_review_id'), table_name='notifications')
    op.drop_index(op.f('idx_reviews_location_created_at'), table_name='reviews')
    op.drop_index(op.f('idx_reviews_location_id'), table_name='reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_reviews_location_id'), 'reviews', ['location_id'], unique=False)
    op.create_index(op.f('idx_reviews_location_created_at'), 'reviews', ['location_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_notifications_review_id'), 'notifications', ['review_id'], unique=False)
    op.create_index(op.f('idx_notifications_location_id'), 'notifications', ['location_id'], unique=False)
    op.create_index(op.f('idx_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('idx_notifications_created_at'), 'notifications', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('locations', 'featured_images',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    # ### end Alembic commands ###
